"""Initial Migration

Revision ID: 5064c78ab677
Revises: 
Create Date: 2025-08-14 17:33:34.782643

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5064c78ab677'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('comments', 'flag_reason',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('messages', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('posts', 'flag_reason',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.add_column('users', sa.Column('email_verified', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'email_verified')
    op.alter_column('posts', 'flag_reason',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('messages', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('comments', 'flag_reason',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
