"""add created_at to categories

Revision ID: 510ad6dae04f
Revises: ce1882a298ce
Create Date: 2025-08-15 07:58:03.331725

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '510ad6dae04f'
down_revision: Union[str, Sequence[str], None] = 'ce1882a298ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('content_warnings', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('content_warnings', 'created_at')
    op.drop_column('categories', 'created_at')
    # ### end Alembic commands ###
